package com.codexa.ai.template;

import com.codexa.ai.model.LlmExplanationResponse;
import com.codexa.persistence.entity.FindingEntity;
import org.springframework.stereotype.Service;

import java.util.List;

@Service
public class DeterministicExplanationTemplateService {

    public LlmExplanationResponse generateFallback(FindingEntity finding) {
        String ruleId = finding.getRuleId() != null ? finding.getRuleId() : "CR-GEN-001";
        String title = finding.getTitle() != null ? finding.getTitle() : "Code Review Finding: " + ruleId;
        String desc = finding.getDescription() != null ? finding.getDescription() : "Deterministic static analysis finding.";
        String impact = finding.getImpact() != null ? finding.getImpact() : "Operational or security defect requiring remediation.";
        String remediation = finding.getRemediation() != null ? finding.getRemediation() : "Refactor code following secure coding guidelines.";
        String suggestedFix = finding.getSuggestedFix() != null ? finding.getSuggestedFix() : "// Apply parameterization, externalization, or input validation.";

        return new LlmExplanationResponse(
                title,
                desc,
                impact,
                remediation,
                suggestedFix,
                "Generated by deterministic rules engine.",
                finding.getReferences() != null && !finding.getReferences().isEmpty() ? finding.getReferences() : List.of("https://owasp.org"),
                finding.isRequiresManualReview()
        );
    }
}
