import React, { useState } from 'react';
import { Copy, Check, Code, ShieldAlert, Sparkles } from 'lucide-react';

export default function CodeDiffViewer({ originalCode, suggestedFix, ruleId, isAiAssisted = true }) {
  const [copied, setCopied] = useState(false);

  const handleCopy = () => {
    if (suggestedFix) {
      navigator.clipboard.writeText(suggestedFix);
      setCopied(true);
      setTimeout(() => setCopied(false), 2500);
    }
  };

  return (
    <div className="space-y-3">
      <div className="flex items-center justify-between">
        <div className="flex items-center space-x-2 text-xs font-semibold text-slate-300">
          <Code className="w-4 h-4 text-emerald-400" />
          <span>Before &amp; After Remediation Comparison</span>
          {isAiAssisted && (
            <span className="inline-flex items-center space-x-1 px-2 py-0.5 rounded-full bg-purple-500/10 text-purple-300 border border-purple-500/30 text-[10px] font-mono font-medium">
              <Sparkles className="w-3 h-3" />
              <span>AI-Assisted Fix</span>
            </span>
          )}
        </div>

        {suggestedFix && (
          <button
            onClick={handleCopy}
            className="flex items-center space-x-1.5 px-3 py-1 bg-emerald-500/10 hover:bg-emerald-500/20 text-emerald-400 border border-emerald-500/30 rounded-lg text-xs font-medium transition-colors"
          >
            {copied ? <Check className="w-3.5 h-3.5 text-emerald-400" /> : <Copy className="w-3.5 h-3.5" />}
            <span>{copied ? 'Copied Secure Code!' : 'Copy Fix'}</span>
          </button>
        )}
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-2 gap-3">
        {/* Vulnerable Code (Before) */}
        <div className="rounded-xl bg-slate-950 border border-rose-500/30 overflow-hidden">
          <div className="px-3.5 py-1.5 bg-rose-500/10 border-b border-rose-500/20 flex items-center justify-between text-[11px] font-semibold text-rose-300">
            <span className="flex items-center space-x-1.5">
              <ShieldAlert className="w-3.5 h-3.5" />
              <span>Vulnerable / Detected Pattern (Before)</span>
            </span>
            <span className="font-mono text-rose-400">{ruleId}</span>
          </div>
          <pre className="p-3.5 text-xs font-mono text-slate-300 overflow-x-auto whitespace-pre leading-relaxed">
            <code>{originalCode || '// No code snippet captured'}</code>
          </pre>
        </div>

        {/* Remediated Code (After) */}
        <div className="rounded-xl bg-slate-950 border border-emerald-500/30 overflow-hidden">
          <div className="px-3.5 py-1.5 bg-emerald-500/10 border-b border-emerald-500/20 flex items-center justify-between text-[11px] font-semibold text-emerald-300">
            <span className="flex items-center space-x-1.5">
              <Check className="w-3.5 h-3.5" />
              <span>Remediated Secure Code (After)</span>
            </span>
            <span className="text-[10px] text-slate-400 font-sans">Requires Human Review</span>
          </div>
          <pre className="p-3.5 text-xs font-mono text-emerald-300 overflow-x-auto whitespace-pre leading-relaxed bg-emerald-950/20">
            <code>{suggestedFix || '// Suggested fix will be generated by AI layer'}</code>
          </pre>
        </div>
      </div>
    </div>
  );
}
