import React, { useState, useMemo } from 'react';
import { Copy, Check, Code2, ShieldAlert, Cpu, Terminal, CheckCircle2 } from 'lucide-react';

export default function CodeDiffViewer({ originalCode, suggestedFix, ruleId, isAiAssisted = true }) {
  const [copied, setCopied] = useState(false);

  // Clean suggested fix: parse out markdown fences or explanation preamble if present
  const cleanedFixCode = useMemo(() => {
    if (!suggestedFix) return '// Suggested fix will be generated by AI layer';
    let code = suggestedFix.trim();
    
    // Check if code contains markdown fences ```lang ... ```
    const match = code.match(/```(?:[a-zA-Z0-9_-]+)?\s*([\s\S]*?)```/);
    if (match && match[1]) {
      return match[1].trim();
    }
    return code;
  }, [suggestedFix]);

  const handleCopy = () => {
    if (cleanedFixCode) {
      navigator.clipboard.writeText(cleanedFixCode);
      setCopied(true);
      setTimeout(() => setCopied(false), 2500);
    }
  };

  // Render lines with numbering and proper soft-wrap to eliminate horizontal scrollbar clutter
  const renderCodeWithLineNumbers = (codeText, type = 'before') => {
    const lines = (codeText || '').split('\n');
    return (
      <div className="flex font-mono text-xs leading-relaxed select-text min-h-[90px]">
        {/* Line Numbers Column */}
        <div className="select-none py-3 px-2 text-right text-slate-400 dark:text-slate-500 bg-slate-950 dark:bg-[#03060f] border-r border-slate-800 shrink-0 font-mono text-[11px] min-w-[36px]">
          {lines.map((_, i) => (
            <div key={i} className="leading-6">{i + 1}</div>
          ))}
        </div>

        {/* Code Content Column with word-wrap */}
        <div className="p-3 text-xs w-full overflow-x-hidden leading-6 font-mono">
          {lines.map((line, i) => (
            <div 
              key={i} 
              className={`px-1.5 rounded transition-colors break-all whitespace-pre-wrap ${
                type === 'before' 
                  ? 'text-rose-300 dark:text-rose-200 bg-rose-950/30 hover:bg-rose-950/45' 
                  : 'text-emerald-300 dark:text-emerald-200 bg-emerald-950/30 hover:bg-emerald-950/45'
              }`}
            >
              {line || ' '}
            </div>
          ))}
        </div>
      </div>
    );
  };

  return (
    <div className="space-y-3 pt-2">
      {/* Top Bar Header */}
      <div className="flex items-center justify-between">
        <div className="flex items-center space-x-2 text-xs font-semibold text-slate-800 dark:text-slate-200 font-display">
          <Terminal className="w-4 h-4 text-blue-600 dark:text-blue-400" />
          <span>Remediation Diff Inspector</span>
          {isAiAssisted && (
            <span className="inline-flex items-center space-x-1 px-2.5 py-0.5 rounded-full bg-blue-500/15 text-blue-700 dark:text-blue-300 border border-blue-500/30 text-[10px] font-mono font-semibold">
              <Cpu className="w-3 h-3 text-blue-500 dark:text-blue-400" />
              <span>Remediation Patch</span>
            </span>
          )}
        </div>

        {cleanedFixCode && (
          <button
            onClick={handleCopy}
            className="flex items-center space-x-1.5 px-3 py-1 bg-blue-500/10 hover:bg-blue-500/20 text-blue-700 dark:text-blue-300 border border-blue-500/30 rounded-xl text-xs font-semibold transition-all shadow-sm active:scale-95 cursor-pointer"
          >
            {copied ? <Check className="w-3.5 h-3.5 text-emerald-500 dark:text-emerald-400" /> : <Copy className="w-3.5 h-3.5" />}
            <span>{copied ? 'Copied Code!' : 'Copy Fix Code'}</span>
          </button>
        )}
      </div>

      {/* Side-by-Side Modern Terminal Windows */}
      <div className="grid grid-cols-1 lg:grid-cols-2 gap-4">
        {/* Vulnerable Code (Before) Terminal Window */}
        <div className="rounded-2xl bg-[#03060f] border border-rose-500/30 overflow-hidden shadow-xl flex flex-col">
          {/* Title Bar */}
          <div className="px-3.5 py-2 bg-slate-900/90 border-b border-rose-500/20 flex items-center justify-between text-xs font-semibold">
            <div className="flex items-center space-x-2">
              <div className="flex items-center space-x-1.5">
                <span className="w-2.5 h-2.5 rounded-full bg-rose-500/80 inline-block" />
                <span className="w-2.5 h-2.5 rounded-full bg-amber-500/80 inline-block" />
                <span className="w-2.5 h-2.5 rounded-full bg-slate-700 inline-block" />
              </div>
              <span className="text-[11px] text-rose-300 font-mono pl-1 flex items-center space-x-1">
                <ShieldAlert className="w-3.5 h-3.5 text-rose-400" />
                <span>Detected Vulnerable Pattern</span>
              </span>
            </div>
            <span className="font-mono text-[10px] text-rose-400 font-bold bg-rose-500/10 px-2 py-0.5 rounded border border-rose-500/30">
              {ruleId}
            </span>
          </div>

          {/* Code Body */}
          <div className="bg-[#050811] flex-1 max-h-[260px] overflow-y-auto custom-scrollbar">
            {renderCodeWithLineNumbers(originalCode, 'before')}
          </div>
        </div>

        {/* Remediated Code (After) Terminal Window */}
        <div className="rounded-2xl bg-[#03060f] border border-emerald-500/30 overflow-hidden shadow-xl flex flex-col">
          {/* Title Bar */}
          <div className="px-3.5 py-2 bg-slate-900/90 border-b border-emerald-500/20 flex items-center justify-between text-xs font-semibold">
            <div className="flex items-center space-x-2">
              <div className="flex items-center space-x-1.5">
                <span className="w-2.5 h-2.5 rounded-full bg-emerald-500/80 inline-block" />
                <span className="w-2.5 h-2.5 rounded-full bg-teal-500/80 inline-block" />
                <span className="w-2.5 h-2.5 rounded-full bg-slate-700 inline-block" />
              </div>
              <span className="text-[11px] text-emerald-300 font-mono pl-1 flex items-center space-x-1">
                <CheckCircle2 className="w-3.5 h-3.5 text-emerald-400" />
                <span>Remediated Implementation</span>
              </span>
            </div>
            <span className="text-[10px] text-emerald-400 font-mono font-bold bg-emerald-500/10 px-2 py-0.5 rounded border border-emerald-500/30">
              Ready to Apply
            </span>
          </div>

          {/* Code Body */}
          <div className="bg-[#050811] flex-1 max-h-[260px] overflow-y-auto custom-scrollbar">
            {renderCodeWithLineNumbers(cleanedFixCode, 'after')}
          </div>
        </div>
      </div>
    </div>
  );
}
