"use client";
import React, { useState, useEffect } from 'react';
import { 
  X, Share2, Copy, Check, Download, ExternalLink, 
  Printer, FileText, Shield, CheckCircle2, AlertTriangle,
  Code2, Eye, Sparkles
} from 'lucide-react';

export default function ExportShareModal({ 
  isOpen, 
  onClose, 
  job, 
  jobId, 
  findings = [], 
  initialFormat = 'pdf' 
}) {
  const [format, setFormat] = useState(initialFormat || 'pdf');
  const [copied, setCopied] = useState(false);
  const [shareSuccess, setShareSuccess] = useState(false);
  const [activeTab, setActiveTab] = useState('actions'); // 'actions' | 'preview'

  // Synchronize format when initialFormat changes
  useEffect(() => {
    if (initialFormat) {
      setFormat(initialFormat);
    }
  }, [initialFormat]);

  if (!isOpen) return null;

  const triggerHaptic = (ms = 12) => {
    try {
      if (typeof window !== 'undefined' && window.navigator?.vibrate) {
        window.navigator.vibrate(ms);
      }
    } catch (_) {}
  };

  const baseUrl = typeof window !== 'undefined' ? window.location.origin : '';
  const exportUrl = `${baseUrl}/api/v1/analyses/${jobId}/export?format=${format === 'pdf' ? 'html' : format}`;
  const reportViewUrl = `${baseUrl}/api/v1/analyses/${jobId}/report?format=${format === 'pdf' ? 'html' : format}&view=true`;
  const reportPrintUrl = `${baseUrl}/api/v1/analyses/${jobId}/report?format=html&view=true&print=true`;

  const critCount = findings.filter(f => (f.severity || '').toUpperCase() === 'CRITICAL').length;
  const highCount = findings.filter(f => (f.severity || '').toUpperCase() === 'HIGH').length;
  const medCount = findings.filter(f => (f.severity || '').toUpperCase() === 'MEDIUM').length;
  const lowCount = findings.filter(f => (f.severity || '').toUpperCase() === 'LOW').length;

  // Executive Share Text for WhatsApp, Slack, Gmail
  const getShareSummary = () => {
    return `🛡️ *CODEXA™ Security & Production Readiness Audit*
━━━━━━━━━━━━━━━━━━━━━━━━━━━━
🎯 *Target:* ${job?.sourceIdentifier || 'Codebase Repository'}
🏆 *Overall Score:* ${job?.overallScore ?? 100}/100 (${job?.verdict || 'REVIEW_COMPLETE'})

📊 *Scorecard Breakdown:*
• Security Defense: ${job?.metrics?.securityScore || 100}/100
• Code Quality: ${job?.metrics?.qualityScore || 100}/100
• Maintainability Index: ${job?.metrics?.maintainabilityScore || 100}/100
• Architectural Health: ${job?.metrics?.architecturalScore || 100}/100

🚨 *Findings Triage:*
• ${critCount} Critical | ${highCount} High | ${medCount} Medium | ${lowCount} Low
• Total Findings: ${findings.length}

📄 *Full Interactive Audit & AI Remediation:*
${reportViewUrl}
━━━━━━━━━━━━━━━━━━━━━━━━━━━━
_Audited deterministically by CODEXA AST Engine_`;
  };

  // Structured Executive Markdown Content
  const getMarkdownContent = () => {
    let md = `# Codexa Production Readiness Report\n\n`;
    md += `> **🛡️ Deterministic AST Security & AI Code Review Audit**  \n`;
    md += `> *Confidential Security Assessment generated by the Codexa Platform.*\n\n`;
    md += `## 📋 Overview & Metadata\n\n`;
    md += `| Attribute | Value |\n`;
    md += `| :--- | :--- |\n`;
    md += `| **Scan Target** | \`${job?.sourceIdentifier || 'Repository'}\` |\n`;
    md += `| **Job ID** | \`${jobId}\` |\n`;
    md += `| **Overall Verdict** | **\`${job?.verdict || 'REVIEW_COMPLETE'}\`** |\n`;
    md += `| **Overall Score** | **\`${job?.overallScore ?? 100} / 100\`** |\n`;
    md += `| **Maintainability Score:** | **\`${job?.metrics?.maintainabilityScore || 100} / 100\`** |\n`;
    md += `| **Architectural Score:** | **\`${job?.metrics?.architecturalScore || 100} / 100\`** |\n`;
    md += `| **Audit Timestamp** | \`${new Date().toISOString()}\` |\n\n`;

    md += `## 📊 Executive Scorecard Breakdown\n\n`;
    md += `| Dimension | Score | Status | Benchmark |\n`;
    md += `| :--- | :---: | :---: | :--- |\n`;
    md += `| 🔒 **Security Readiness** | **${job?.metrics?.securityScore || 100}/100** | ${(job?.metrics?.securityScore || 100) >= 80 ? '🟢 PASSED' : '🟡 WARNING'} | \`>= 80.0\` |\n`;
    md += `| 🧹 **Code Quality** | **${job?.metrics?.qualityScore || 100}/100** | ${(job?.metrics?.qualityScore || 100) >= 80 ? '🟢 PASSED' : '🟡 WARNING'} | \`>= 80.0\` |\n`;
    md += `| ⚙️ **Operational Reliability** | **${job?.metrics?.operationsScore || 100}/100** | ${(job?.metrics?.operationsScore || 100) >= 80 ? '🟢 PASSED' : '🟡 WARNING'} | \`>= 80.0\` |\n`;
    md += `| 📐 **Maintainability Index** | **${job?.metrics?.maintainabilityScore || 100}/100** | ${(job?.metrics?.maintainabilityScore || 100) >= 75 ? '🟢 PASSED' : '🟡 WARNING'} | \`>= 75.0\` |\n`;
    md += `| 🏗️ **Architectural Health** | **${job?.metrics?.architecturalScore || 100}/100** | ${(job?.metrics?.architecturalScore || 100) >= 75 ? '🟢 PASSED' : '🟡 WARNING'} | \`>= 75.0\` |\n\n`;

    md += `### 🚨 Findings Triage Distribution\n\n`;
    md += `| 🔴 Critical | 🟠 High | 🟡 Medium | 🔵 Low | Total Findings |\n`;
    md += `| :---: | :---: | :---: | :---: | :---: |\n`;
    md += `| **${critCount}** | **${highCount}** | **${medCount}** | **${lowCount}** | **${findings.length}** |\n\n`;

    md += `## 🔍 Findings Catalog\n\n`;
    md += `| Rule ID | Severity | Category | File | Line | Title | Priority |\n`;
    md += `| :--- | :---: | :--- | :--- | :---: | :--- | :---: |\n`;
    findings.forEach(f => {
      md += `| \`${f.ruleId}\` | ${f.severity} | ${f.category || 'SECURITY'} | \`${f.filePath}\` | \`${f.startLine}\` | ${f.title} | \`${f.priorityScore || 80.0}\` |\n`;
    });

    md += `\n## 🛠️ Detailed Remediations & Patches\n\n`;
    if (findings.length === 0) {
      md += `✅ *Zero security vulnerabilities or architectural defects identified.*\n\n`;
    } else {
      findings.forEach(f => {
        md += `### [${f.severity}] ${f.ruleId} - ${f.title}\n\n`;
        md += `- **Severity:** \`${f.severity}\`\n`;
        md += `- **Location:** \`${f.filePath}:${f.startLine}\`\n`;
        md += `- **OWASP:** \`${f.owaspMapping || 'N/A'}\`\n`;
        md += `- **Priority Weight:** \`${f.priorityScore || 80.0}\`\n\n`;
        if (f.description) md += `**Vulnerability Analysis:**  \n${f.description}\n\n`;
        if (f.evidenceMasked) md += `#### ❌ Vulnerable Snippet:\n\`\`\`\n${f.evidenceMasked}\n\`\`\`\n\n`;
        if (f.suggestedFix) md += `#### ✅ Suggested Remediation Patch:\n\`\`\`\n${f.suggestedFix}\n\`\`\`\n\n`;
        md += `---\n\n`;
      });
    }

    md += `\n---\n*Report generated by **CODEXA Platform** — Zero-Bytecode Static AST Code Review Engine.*\n`;
    return md;
  };

  // Structured Schema-Compliant JSON Content
  const getJsonContent = () => {
    return JSON.stringify({
      "$schema": "https://codexa.dev/schemas/audit-report-v1.json",
      "auditId": jobId,
      "scanTarget": job?.sourceIdentifier || "Repository",
      "sourceType": job?.sourceType || "SOURCE",
      "generatedAt": new Date().toISOString(),
      "overallVerdict": job?.verdict || "REVIEW_COMPLETE",
      "overallScore": job?.overallScore ?? 100.0,
      "metrics": {
        "securityScore": job?.metrics?.securityScore ?? 100.0,
        "qualityScore": job?.metrics?.qualityScore ?? 100.0,
        "maintainabilityScore": job?.metrics?.maintainabilityScore ?? 100.0,
        "architecturalScore": job?.metrics?.architecturalScore ?? 100.0,
        "operationsScore": job?.metrics?.operationsScore ?? 100.0,
        "totalFilesScanned": job?.metrics?.totalFiles ?? 0,
        "scanDurationMs": job?.metrics?.durationMs ?? 0
      },
      "triage": {
        "critical": critCount,
        "high": highCount,
        "medium": medCount,
        "low": lowCount,
        "total": findings.length
      },
      "findings": findings.map(f => ({
        "ruleId": f.ruleId,
        "title": f.title,
        "severity": f.severity,
        "category": f.category || "SECURITY",
        "confidence": f.confidence || "HIGH",
        "filePath": f.filePath,
        "startLine": f.startLine,
        "endLine": f.endLine,
        "owaspMapping": f.owaspMapping || null,
        "priorityScore": f.priorityScore,
        "description": f.description,
        "impact": f.impact,
        "vulnerableSnippet": f.evidenceMasked || null,
        "remediationPatch": f.suggestedFix || null
      }))
    }, null, 2);
  };

  // Generate format-specific raw content for copying
  const getRawContent = () => {
    if (format === 'json') return getJsonContent();
    if (format === 'md') return getMarkdownContent();
    return getShareSummary();
  };

  // Resilient clipboard copy with textarea fallback for Android WebViews
  const copyTextToClipboard = (text) => {
    if (navigator.clipboard && navigator.clipboard.writeText) {
      navigator.clipboard.writeText(text).catch(() => {
        fallbackCopy(text);
      });
      return;
    }
    fallbackCopy(text);
  };

  const fallbackCopy = (text) => {
    try {
      const textarea = document.createElement('textarea');
      textarea.value = text;
      textarea.style.position = 'fixed';
      textarea.style.opacity = '0';
      document.body.appendChild(textarea);
      textarea.focus();
      textarea.select();
      document.execCommand('copy');
      document.body.removeChild(textarea);
    } catch (e) {
      console.warn('Fallback copy error:', e);
    }
  };

  const handleNativeShare = async () => {
    triggerHaptic(15);
    try {
      if (navigator.share) {
        await navigator.share({
          title: `Codexa Audit: ${job?.sourceIdentifier || 'Repository'}`,
          text: getShareSummary(),
          url: reportViewUrl,
        });
        setShareSuccess(true);
        setTimeout(() => setShareSuccess(false), 2500);
      } else {
        handleCopyContent();
      }
    } catch (err) {
      if (err.name !== 'AbortError') {
        handleCopyContent();
      }
    }
  };

  const handleCopyContent = () => {
    triggerHaptic(15);
    const text = getRawContent();
    copyTextToClipboard(text);
    setCopied(true);
    setTimeout(() => setCopied(false), 2500);
  };

  const handleOpenBrowser = () => {
    triggerHaptic(10);
    const targetUrl = format === 'pdf' ? reportPrintUrl : reportViewUrl;
    window.open(targetUrl, '_blank');
  };

  const rawPreview = getRawContent();
  const previewLines = rawPreview.split('\n').slice(0, 16).join('\n');

  return (
    <div className="fixed inset-0 z-50 flex items-end sm:items-center justify-center p-0 sm:p-4 bg-black/80 backdrop-blur-md animate-in fade-in duration-200 select-none">
      <div 
        className="w-full sm:max-w-lg bg-[#0D121F] rounded-t-3xl sm:rounded-3xl border border-slate-800 shadow-2xl overflow-hidden flex flex-col max-h-[92vh] pb-[max(1.25rem,env(safe-area-inset-bottom))]"
        onClick={(e) => e.stopPropagation()}
      >
        {/* Handle bar on mobile */}
        <div className="w-12 h-1.5 bg-slate-700 rounded-full mx-auto mt-3 sm:hidden" />

        {/* Modal Header */}
        <div className="flex items-center justify-between px-5 pt-3 sm:pt-4 pb-3 border-b border-slate-800">
          <div className="flex items-center space-x-2.5">
            <div className="w-8 h-8 rounded-xl bg-blue-500/15 text-blue-400 border border-blue-500/30 flex items-center justify-center font-bold shadow-sm">
              <Download className="w-4 h-4" />
            </div>
            <div>
              <h3 className="text-sm font-bold text-white font-display flex items-center gap-1.5">
                <span>Export &amp; Share Audit</span>
                <span className="text-[9px] font-mono font-bold uppercase bg-blue-500/20 text-blue-400 px-1.5 py-0.2 rounded border border-blue-500/30">v2.4</span>
              </h3>
              <p className="text-[10.5px] text-slate-400 font-mono truncate max-w-[240px]">
                {job?.sourceIdentifier || 'Codebase Report'}
              </p>
            </div>
          </div>
          <button
            onClick={onClose}
            className="p-1.5 rounded-full hover:bg-slate-800 text-slate-400 hover:text-white transition-colors cursor-pointer active:scale-90"
            aria-label="Close dialog"
          >
            <X className="w-5 h-5" />
          </button>
        </div>

        {/* Format Selector Tabs */}
        <div className="px-5 pt-3 pb-2">
          <div className="grid grid-cols-4 gap-1.5 p-1 bg-slate-900/90 rounded-2xl border border-slate-800">
            {[
              { id: 'pdf', label: 'PDF Print', icon: Printer, color: 'text-rose-400' },
              { id: 'html', label: 'HTML Report', icon: FileText, color: 'text-blue-400' },
              { id: 'md', label: 'Markdown', icon: FileText, color: 'text-violet-400' },
              { id: 'json', label: 'JSON Data', icon: Code2, color: 'text-emerald-400' }
            ].map(tab => {
              const TabIcon = tab.icon;
              const isActive = format === tab.id;
              return (
                <button
                  key={tab.id}
                  onClick={() => {
                    triggerHaptic(8);
                    setFormat(tab.id);
                  }}
                  className={`py-2 px-1 rounded-xl text-xs font-semibold flex flex-col items-center justify-center space-y-1 transition-all cursor-pointer ${
                    isActive 
                      ? 'bg-slate-800 text-white shadow-sm border border-slate-700' 
                      : 'text-slate-400 hover:text-white'
                  }`}
                >
                  <TabIcon className={`w-4 h-4 ${tab.color}`} />
                  <span className="text-[10.5px] font-mono leading-tight">{tab.label}</span>
                </button>
              );
            })}
          </div>
        </div>

        {/* Subtab Toggle: Format Details vs Live Code Preview */}
        <div className="px-5 pt-1 pb-1 flex items-center justify-between">
          <div className="flex items-center space-x-1 p-0.5 bg-slate-900 rounded-lg border border-slate-800 text-[10px] font-mono">
            <button
              onClick={() => setActiveTab('actions')}
              className={`px-2 py-1 rounded-md transition-all ${activeTab === 'actions' ? 'bg-slate-800 text-white font-bold' : 'text-slate-400'}`}
            >
              Details
            </button>
            <button
              onClick={() => setActiveTab('preview')}
              className={`px-2 py-1 rounded-md transition-all flex items-center space-x-1 ${activeTab === 'preview' ? 'bg-slate-800 text-white font-bold' : 'text-slate-400'}`}
            >
              <Eye className="w-3 h-3" />
              <span>Live Preview</span>
            </button>
          </div>
          <span className="text-[10px] font-mono text-emerald-400 flex items-center space-x-1">
            <span className="w-1.5 h-1.5 rounded-full bg-emerald-400 animate-pulse" />
            <span>Ready to Export</span>
          </span>
        </div>

        {/* Tab Body: Actions Details or Live Preview Box */}
        <div className="px-5 py-2">
          {activeTab === 'actions' ? (
            <div className="p-3 rounded-2xl bg-slate-900/60 border border-slate-800/80 space-y-1.5 text-left">
              <div className="flex items-center justify-between">
                <span className="text-xs font-bold text-white font-display">
                  {format === 'pdf' && 'Executive PDF Audit Report (Print Ready)'}
                  {format === 'html' && 'Standalone Interactive HTML Audit'}
                  {format === 'md' && 'GitHub-Flavored Markdown Security Advisory'}
                  {format === 'json' && 'Structured Machine-Readable Audit JSON'}
                </span>
                <span className="px-2 py-0.5 rounded-full text-[9px] font-mono font-bold bg-blue-500/15 text-blue-400 border border-blue-500/30">
                  {format.toUpperCase()}
                </span>
              </div>
              <p className="text-[11px] text-slate-400 leading-relaxed font-sans">
                {format === 'pdf' && 'Opens pristine executive white-paper layout in browser with automatic print dialog to save as PDF or print.'}
                {format === 'html' && 'Complete standalone audit report with executive scorecards, triage bars, and syntax-styled code diffs.'}
                {format === 'md' && 'Formatted with summary tables, triage distribution, and code blocks ready to paste into GitHub PR reviews.'}
                {format === 'json' && 'Complete JSON payload with all metric scores, rule IDs, file locations, line numbers, and AI remediation patches.'}
              </p>
            </div>
          ) : (
            <div className="p-3 rounded-2xl bg-[#060913] border border-slate-800 text-left font-mono text-[10.5px] leading-relaxed overflow-hidden">
              <div className="flex items-center justify-between pb-1.5 mb-1.5 border-b border-slate-800/60 text-[10px] text-slate-500">
                <span>PREVIEW SNIPPET</span>
                <span>{previewLines.split('\n').length} lines</span>
              </div>
              <pre className="text-slate-300 max-h-24 overflow-y-auto whitespace-pre-wrap font-mono">
                {previewLines}
              </pre>
            </div>
          )}
        </div>

        {/* Action Buttons Grid */}
        <div className="px-5 py-3 space-y-2.5">
          {/* Primary Action 1: Native Mobile Share Sheet */}
          <button
            onClick={handleNativeShare}
            className="w-full py-3 px-4 rounded-xl bg-blue-600 hover:bg-blue-500 text-white text-xs font-bold font-display flex items-center justify-center space-x-2 shadow-lg shadow-blue-500/25 active:scale-98 transition-all cursor-pointer"
          >
            {shareSuccess ? <Check className="w-4 h-4 text-emerald-300" /> : <Share2 className="w-4 h-4" />}
            <span>{shareSuccess ? 'Report Link & Summary Shared!' : 'Share via Mobile Apps (WhatsApp, Slack, Mail...)'}</span>
          </button>

          <div className="grid grid-cols-2 gap-2">
            {/* Copy Content / Summary Button */}
            <button
              onClick={handleCopyContent}
              className="py-2.5 px-3 rounded-xl bg-slate-900 hover:bg-slate-800 text-slate-200 text-xs font-semibold flex items-center justify-center space-x-1.5 border border-slate-800 active:scale-98 transition-all cursor-pointer"
            >
              {copied ? <Check className="w-4 h-4 text-emerald-400" /> : <Copy className="w-4 h-4" />}
              <span>{copied ? 'Copied to Clipboard!' : `Copy ${format.toUpperCase()}`}</span>
            </button>

            {/* Direct Open in Browser / Save PDF */}
            <button
              onClick={handleOpenBrowser}
              className="py-2.5 px-3 rounded-xl bg-slate-900 hover:bg-slate-800 text-slate-200 text-xs font-semibold flex items-center justify-center space-x-1.5 border border-slate-800 active:scale-98 transition-all cursor-pointer"
            >
              {format === 'pdf' ? (
                <Printer className="w-4 h-4 text-rose-400 shrink-0" />
              ) : (
                <ExternalLink className="w-4 h-4 text-blue-400 shrink-0" />
              )}
              <span>{format === 'pdf' ? 'Print / Save PDF' : 'Open in Browser'}</span>
            </button>
          </div>

          {/* Direct File Download Anchor Link (Native Download via browser) */}
          <a
            href={exportUrl}
            target="_blank"
            rel="noopener noreferrer"
            download={`codexa-report-${jobId}.${format === 'markdown' || format === 'md' ? 'md' : format === 'pdf' ? 'html' : format}`}
            onClick={() => triggerHaptic(8)}
            className="w-full py-2.5 px-3 rounded-xl bg-slate-900/60 border border-slate-800 text-[11px] font-mono text-slate-400 hover:text-blue-400 flex items-center justify-center space-x-1.5 transition-colors active:scale-98"
          >
            <Download className="w-3.5 h-3.5 text-blue-400" />
            <span>Direct File Download (.{(format === 'markdown' || format === 'md' ? 'md' : format === 'pdf' ? 'html' : format)})</span>
          </a>
        </div>
      </div>
    </div>
  );
}
